; include at very top
; include-file = ~/.cache/wal/colors-waybar.css
; #ff = 100% opaque
; #e6 = 90
; #cc 80
; #99 60
; #00 0
[colors]
trans1 = #80000000
trans2 = #00
bg = #00${xrdb:background}
fg = ${xrdb:foreground}
c1     = ${xrdb:color1}
c2     = ${xrdb:color2}
c3     = ${xrdb:color3}
c4     = ${xrdb:color4}
c5     = ${xrdb:color5}
c6     = ${xrdb:color6}
c7     = ${xrdb:color7}
c8     = ${xrdb:color8}
c9     = ${xrdb:color9}
c10     = ${xrdb:color10}
c11     = ${xrdb:color11}
c12     = ${xrdb:color12}
c13     = ${xrdb:color13}
c14     = ${xrdb:color14}
c15     = ${xrdb:color15}
