;
;	 ██████╗ ██████╗ ██╗      ██████╗ ██████╗ ███████╗
;	██╔════╝██╔═══██╗██║     ██╔═══██╗██╔══██╗██╔════╝
;	██║     ██║   ██║██║     ██║   ██║██████╔╝███████╗
;	██║     ██║   ██║██║     ██║   ██║██╔══██╗╚════██║
;	 ██████╗╚██████╔╝███████╗╚██████╔╝██║  ██║███████║
; 	 ╚═════╝ ╚═════╝ ╚══════╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝
;
;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[color]

alpha = #0000ffff
bg1 = #383d49
background = #0b181a
fg = #c2c5c5


;; for 50% transparent
trans1 = #80000000 
;; 100% transparent
trans2 = #00


;; colors
;black = #3B4252
red1 = #4A5758
green1 = #59625E
yellow1 = #62675E
blue1 = #535F60
ocean = #6381C4
bluedark = #3D59A1
magenta1 = #596362
indigo1 = #6C77BB
indigolight1 = #808bcf
cyan1 = #656C66
white = #ECEFF4
teal = #8FBCBB
;orange = 
;pink = 


;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
